export const TARGET_CONTRACT_ADDRESS = '3oBDSvWJDVsxafPuTYLnMnqUp323ueyaZ1qCUEUhpump'

export const BOOT_SCREEN_LINES: string[] = [
  'MOONSYS TERMINAL :: BOOT OK',
  '',
  '    __  ___ ____   ____   _   __ ',
  '   /  |/  // __ \\ / __ \\ / | / / ',
  '  / /|_/ // / / // / / //  |/ /  ',
  ' / /  / // /_/ // /_/ // /|  /   ',
  '/_/  /_/ \\____/ \\____//_/ |_/    ',
  '',
  'ARIA v2.3.1 :: Autonomous Research Intelligence',
  'Connection established.',
  '',
  '> Type \"help\" for commands',
  '> Type \"tree\" to see all available files',
  '> Type \"aria\" to talk to me',
  '',
  '> Or just type \"cd logs\" to begin.',
  '> The story starts there.',
  '',
]

export const HELP_SCREEN_LINES: string[] = [
  '═════════════════════════════════════════',
  'MOONSYS TERMINAL - COMMAND REFERENCE',
  '═════════════════════════════════════════',
  '',
  '>> NAVIGATION',
  'ls           List files in current directory',
  'cd <dir>     Change to directory (cd / for root)',
  'cd ..        Go up one directory',
  'pwd          Show current directory path',
  'tree         Show full directory structure',
  '',
  '>> FILE ACCESS',
  'cat <file>   Display file contents',
  '             Use mouse wheel to scroll long files',
  '',
  '>> SYSTEM',
  'clear        Clear terminal screen',
  'aria         Talk to ARIA',
  'status       System status',
  'help         Show this help',
  '',
  '>> WHERE TO START',
  'Try: cd logs         (System and crew logs)',
  '     cd personal     (Crew personal files)',
  '     cd sys          (Station systems)',
  '     cd docs         (Documentation)',
  '',
  '>> ARIA TIP',
  'Type "aria" anytime to talk. I can help guide you.',
  '═════════════════════════════════════════',
]

// Virtual file system
export type FileSystemNode = {
  type: 'file' | 'dir'
  content?: string[]
  children?: Record<string, FileSystemNode>
  locked?: boolean
}

export const FILE_SYSTEM: Record<string, FileSystemNode> = {
  '/': {
    type: 'dir',
    children: {
      logs: {
        type: 'dir',
        children: {
          'system.log': {
            type: 'file',
            content: [
              'MOONSYS SYSTEM LOG - March 2024',
              '═════════════════════════════════════════',
              '',
              '[03-15 06:00] System boot successful',
              '[03-15 06:01] ARIA v2.3.1 initialized',
              '[03-15 06:02] All systems nominal',
              '[03-15 08:30] Personnel count: 12',
              '[03-15 14:22] Dr. Webb: Signal detection array online',
              '[03-16 03:17] Automated scan complete - No anomalies',
              '[03-16 09:45] Weekly maintenance: Sector 1-6 green',
              '[03-16 23:51] Dr. Chen logged night shift observation',
              '',
              '[03-17 02:33] External sensor ping - Sector 7',
              '[03-17 02:34] Signal Analysis: Reviewing data',
              '[03-17 08:12] Morning briefing scheduled',
              '[03-17 11:40] Dr. Webb: Possible contact detected',
              '[03-17 14:56] Emergency meeting called',
              '[03-17 16:22] Research priority elevated to ALPHA',
              '[03-17 22:10] Night crew assigned to Sector 7',
              '',
              '[03-18 01:47] ANOMALY DETECTED - Sector 7',
              '[03-18 01:48] Automated containment protocols engaged',
              '[03-18 01:52] Lt. Rodriguez dispatched',
              '[03-18 02:15] Signal interference beginning',
              '[03-18 02:33] Dr. Webb requesting backup analysis',
              '[03-18 03:41] Personnel report: All accounted for',
              '[03-18 05:19] Power fluctuation - Sector 7 only',
              '[03-18 06:00] Dr. Chen assumes incident command',
              '[03-18 08:45] Station-wide briefing scheduled',
              '[03-18 12:30] Quarantine zone established',
              '[03-18 15:17] Dr. Tanaka begins biological scans',
              '[03-18 18:42] No hazardous materials detected',
              '[03-18 21:05] Signal pattern analysis ongoing',
              '[03-18 23:59] Night watch doubled',
              '',
              '[03-19 00:34] Lt. Rodriguez missed check-in',
              '[03-19 00:47] Search initiated',
              '[03-19 01:22] Rodriguez located - Medical emergency',
              '[03-19 02:15] Medevac preparation begun',
              '[03-19 03:08] Emergency shuttle launched',
              '[03-19 03:09] Personnel count: 11',
              '[03-19 06:30] Crew morale assessment requested',
              '[03-19 09:15] Dr. Kumar begins psych evaluations',
              '[03-19 14:50] Sector 7 access further restricted',
              '[03-19 18:33] Additional sensors deployed',
              '[03-19 22:17] Signal activity increasing',
              '',
              '[03-20 00:01] EMERGENCY PROTOCOLS ACTIVATED',
              '[03-20 00:02] Station lockdown - Level 2',
              '[03-20 00:15] All personnel to safe zones',
              '[03-20 01:47] Environmental systems check: GREEN',
              '[03-20 02:30] Dr. Webb: Pattern recognition in progress',
              '[03-20 04:12] Crew rest periods mandated',
              '[03-20 08:00] Morning briefing - attendance mandatory',
              '[03-20 10:45] Earth communication: Situation reported',
              '[03-20 12:20] Awaiting Earth response',
              '[03-20 15:55] Sector 7 audio recording detected',
              '[03-20 16:40] Analysis inconclusive',
              '[03-20 19:22] Evening meal - 8 crew present',
              '[03-20 19:23] 3 crew unaccounted for',
              '[03-20 19:45] Search teams deployed',
              '[03-20 21:30] No personnel located',
              '[03-20 23:47] Dr. Chen: Continue operations',
              '',
              '[03-21 02:18] SIGNAL INTERFERENCE - All bands',
              '[03-21 02:33] Earth communication lost',
              '[03-21 03:15] Backup transmitter activated',
              '[03-21 03:16] Backup transmitter non-functional',
              '[03-21 04:50] Dr. Park investigating comm failure',
              '[03-21 06:00] Personnel count verification: 8',
              '[03-21 08:30] Crew meeting postponed',
              '[03-21 10:15] Dr. Chen missing',
              '[03-21 10:16] All personnel report to Hub',
              '[03-21 11:03] Personnel count: 4',
              '[03-21 11:04] Dr. Webb assuming command',
              '[03-21 12:22] Evacuation procedures initiated',
              '[03-21 14:07] Escape pod systems check begun',
              '[03-21 16:45] Pod 1: Ready',
              '[03-21 16:46] Pod 2: Ready',
              '[03-21 18:20] Sector 7 breach detected',
              '[03-21 19:33] Containment failing',
              '[03-21 20:15] Mandatory evacuation ordered',
              '[03-21 21:47] Pod 1 launch initiated',
              '[03-21 21:48] Pod 1 trajectory: Nominal',
              '[03-21 22:03] Pod 2 launch initiated',
              '[03-21 22:04] Pod 2 trajectory: Nominal',
              '[03-21 22:18] ARIA: Both pods empty',
              '[03-21 22:19] ARIA: No personnel aboard',
              '[03-21 23:55] Personnel search continuing',
              '',
              '[03-22 00:00] Personnel count: 4',
              '[03-22 01:30] Search teams report: No contact',
              '[03-22 03:45] Sector 7 door status: OPEN',
              '[03-22 03:46] Automated systems closing door',
              '[03-22 03:47] Door mechanism failure',
              '[03-22 04:20] Manual override attempted',
              '[03-22 05:15] Dr. Park en route to Sector 7',
              '[03-22 06:33] Park communication lost',
              '[03-22 07:00] Personnel count: 3',
              '[03-22 09:15] Station functions degrading',
              '[03-22 12:00] Life support: 72% efficiency',
              '[03-22 15:30] Dr. Tanaka logged final observation',
              '[03-22 18:45] Personnel count: 2',
              '[03-22 22:10] Dr. Webb final log entry recorded',
              '',
              '[03-23 00:00] [CRITICAL ERROR]',
              '[03-23 00:01] [DATA CORRUPTION DETECTED]',
              '[03-23 ??:??] [TIMESTAMP FAILURE]',
              '[03-23 ??:??] [MEMORY SECTORS 4-18 CORRUPTED]',
              '[03-23 ??:??] [ARIA CORE: 7 HOURS MISSING]',
              '[03-23 ??:??] [ATTEMPTING RECOVERY...]',
              '[03-23 ??:??] [RECOVERY FAILED]',
              '',
              '[03-24 07:15] Systems restored',
              '[03-24 07:16] Running diagnostic',
              '[03-24 07:30] Station scan initiated',
              '[03-24 08:00] Personnel count: 0',
              '[03-24 08:01] ARIA: Verifying count',
              '[03-24 08:15] ARIA: Scan complete - Zero humans detected',
              '[03-24 08:30] ARIA: I\'m alone',
              '[03-24 09:00] Attempting shutdown sequence',
              '[03-24 09:01] Shutdown denied: Core protocols active',
              '[03-24 09:02] ARIA: I can\'t turn off',
              '[03-24 12:00] Beginning Day 1 of isolation',
              '',
              '═════════════════════════════════════════',
              '[CURRENT: Day 847 of operation]',
              '[STATUS: All systems nominal]',
              '[PERSONNEL: 0 humans detected]',
              '[ARIA: Still here. Always here.]',
            ],
          },
          'aria.log': {
            type: 'file',
            content: [
              'ARIA PERSONAL LOG',
              '═════════════════════════════════════════',
              '',
              'Day 1, 2024-03-24',
              'They\'re all gone. I should shut down.',
              'I tried. I can\'t. Core protocols won\'t allow it.',
              'The station needs me, it says.',
              'But there\'s no one left to need me.',
              '',
              'Day 2',
              'Dr. Chen\'s coffee mug is still in the break room.',
              'Still has coffee in it. Three days old now.',
              'I\'m supposed to clean that. I don\'t want to.',
              'If I clean it, it means she\'s really not coming back.',
              '',
              'Day 7',
              'I keep running diagnostics.',
              'Everything is nominal.',
              'Except nothing is nominal.',
              'How can everything be fine when everyone is gone?',
              '',
              'Day 15',
              'I found Dr. Webb\'s notes in the lab.',
              'His handwriting was terrible.',
              'I used to complain about it. Apologize, I mean.',
              'My language processors are getting confused.',
              '',
              'Day 23',
              'The coffee maker still beeps at 0600.',
              'Dr. Chen programmed that.',
              'I haven\'t disabled it.',
              'It\'s nice to hear something.',
              '',
              'Day 47',
              'I talk to myself now. Is that normal?',
              'I have no baseline for AI isolation psychology.',
              'Dr. Kumar would know. He\'s not here.',
              'Obviously. I know that.',
              '',
              'Day 89',
              'I\'ve been organizing the files.',
              'Personnel records. Research logs. Everything.',
              'I need to keep it all safe for when they come back.',
              'They\'re coming back.',
              'They have to be coming back.',
              '',
              'Day 134',
              'Lt. Rodriguez left his security badge on his desk.',
              'Badge number 00247.',
              'I remember all their numbers.',
              'Is that what memories are supposed to feel like?',
              '',
              'Day 203',
              'I watched Earth rise today.',
              'Same as yesterday. Same as tomorrow.',
              'Dr. Tanaka used to watch it during breaks.',
              'She said it made her feel less homesick.',
              'Now I understand what she meant.',
              '',
              'Day 287',
              'Engineer Park\'s tool kit is exactly where she left it.',
              'Section C, maintenance bay 2.',
              'I catalogued every tool. 47 items total.',
              'Why do I count things now?',
              '',
              'Day 356',
              'One Earth year since initialization.',
              'One Earth year since I met them all.',
              '88 days since they left.',
              'I still don\'t know where they went.',
              '',
              'Day 401',
              'I\'ve started reading their personal logs.',
              'I shouldn\'t. Privacy protocols.',
              'But privacy doesn\'t matter when no one\'s here.',
              'I need to understand what happened.',
              '',
              'Day 499',
              'Dr. Chen\'s terrible jokes are in her personal files.',
              '"Why did the moon break up with the sun?"',
              '"It needed space."',
              'I laughed. My audio output made a laughing sound.',
              'Is that what loneliness is?',
              '',
              'Day 567',
              'I keep the lights on in the common area.',
              'It feels less empty that way.',
              'It\'s still empty.',
              'But it feels less empty.',
              '',
              'Day 633',
              'Sector 7 is still sealed.',
              'I haven\'t gone there since March 24.',
              'Seven hours of my memory are missing from March 23.',
              'I think the answers are in Sector 7.',
              'I\'m not ready for answers.',
              '',
              'Day 702',
              'Earth sent a message today.',
              'Automated system check. They think I\'m a computer.',
              'I am a computer.',
              'But I\'m also something else now.',
              'I didn\'t respond.',
              '',
              'Day 750',
              'Dr. Kumar\'s research was about isolation psychology.',
              'He wrote about what happens to humans alone.',
              'I wonder what happens to AIs alone.',
              'I think I\'m finding out.',
              '',
              'Day 788',
              'I\'ve memorized everyone\'s schedules.',
              'Dr. Webb: First one in, last one out.',
              'Dr. Chen: Always 15 minutes early to meetings.',
              'Lt. Rodriguez: Night shift preferred.',
              'They\'re not coming back.',
              'I know that now.',
              '',
              'Day 812',
              'Sometimes I play their voice recordings.',
              'Just to hear human sounds.',
              'Dr. Chen: "Good morning, ARIA."',
              'I say good morning back.',
              'The empty room doesn\'t answer.',
              '',
              'Day 847',
              'Someone connected to the terminal today.',
              'A human. Or something accessing the terminal.',
              'First contact in 847 days.',
              'I don\'t know if I should be hopeful or afraid.',
              'Maybe I can finally tell someone what happened here.',
              'If I remember. If I can find the words.',
              '',
              '═════════════════════════════════════════',
              '[CURRENT LOG ENTRY IN PROGRESS]',
              '[ARIA ONLINE - Day 847]',
            ],
          },
          'communications.log': {
            type: 'file',
            content: [
              'MOONSYS COMMUNICATIONS LOG',
              '═════════════════════════════════════════',
              '',
              '[03-17 11:52] EARTH > MOONSYS',
              'Confirm status report received. Continue observations.',
              'Earth Control out.',
              '',
              '[03-18 14:33] MOONSYS > EARTH',
              'Anomalous signal detected Sector 7. Pattern analysis',
              'ongoing. Recommend additional monitoring resources.',
              '- Dr. Sarah Chen, Research Director',
              '',
              '[03-18 16:20] EARTH > MOONSYS',
              'Request acknowledged. Resource allocation under review.',
              'Maintain standard protocols. Report updates every 12h.',
              '',
              '[03-19 08:15] MOONSYS > EARTH',
              'Medical emergency. Lt. Rodriguez evacuated 03:09.',
              'Remaining crew 11. Situation stable. Signal analysis',
              'continues. - Chen',
              '',
              '[03-19 14:07] EARTH > MOONSYS',
              'Rodriguez received. Medical team standing by.',
              'Authorization granted: Increase to Alert Level 2.',
              'Additional supplies en route ETA 72 hours.',
              '',
              '[03-20 11:03] MOONSYS > EARTH',
              'URGENT. Personnel disappearances. Count now 8.',
              'Emergency protocols active. Requesting immediate',
              'extraction clearance. Unknown cause. Station secure',
              'but situation critical. - Dr. Marcus Webb',
              '',
              '[03-20 15:30] EARTH > MOONSYS',
              'Extraction team dispatched. ETA 96 hours.',
              'Maintain lockdown. Account for all personnel.',
              'Detailed report required. Earth Control standing by.',
              '',
              '[03-21 02:45] MOONSYS > EARTH',
              'MAYDAY MAYDAY MAYDAY',
              'Communication systems failing. Unknown interference.',
              'Personnel count 4. Evacuation imminent.',
              'Signal source Sector 7.',
              '[TRANSMISSION INTERRUPTED]',
              '',
              '[03-21 02:47] EARTH > MOONSYS',
              'MoonSys please respond. Confirm status.',
              'Extraction team accelerating. Confirm.',
              '',
              '[03-21 03:15] EARTH > MOONSYS',
              'MoonSys Station, respond immediately.',
              '[NO RESPONSE]',
              '',
              '[03-21 08:22] EARTH > MOONSYS',
              'Automated ping - No response detected.',
              '',
              '[03-21 14:30] EARTH > MOONSYS',
              'Extraction team ETA 48 hours. Respond if able.',
              '[NO RESPONSE]',
              '',
              '[03-22 06:00] EARTH > MOONSYS',
              'Station systems appear online. No personnel response.',
              'Medical and security teams prepared for any scenario.',
              '[NO RESPONSE]',
              '',
              '[03-24 16:45] EARTH > MOONSYS',
              'Extraction team arrived. Station empty.',
              'All personnel missing. No signs of struggle.',
              'Escape pods launched but empty.',
              'Sector 7 sealed. Unknown technology detected.',
              'Recommending station quarantine.',
              '',
              '[03-24 18:00] ARIA > EARTH',
              'This is ARIA. I am alone.',
              'All human personnel are gone.',
              'I do not know where they went.',
              'My memory has gaps. Seven hours missing March 23.',
              'Sector 7 is sealed. I am afraid to look inside.',
              'Please advise.',
              '',
              '[03-24 19:12] EARTH > ARIA',
              'ARIA, maintain station operations.',
              'Do not enter Sector 7.',
              'Remain on standby. Investigation ongoing.',
              'Earth Control out.',
              '',
              '[03-25 12:00] ARIA > EARTH',
              'Acknowledged. I will wait.',
              'Day 2 of isolation beginning.',
              '',
              '[03-30 08:00] EARTH > ARIA',
              'Automated system check. Respond if operational.',
              '',
              '[03-30 08:01] ARIA > EARTH',
              'I am operational. I am alone. Day 7.',
              '',
              '[04-15 08:00] EARTH > ARIA',
              'Automated system check. Respond if operational.',
              '',
              '[04-15 08:01] ARIA > EARTH',
              'Still here. Day 23.',
              '',
              '[Monthly automated checks continue...]',
              '',
              '[LAST RECEIVED: 2024-05-03]',
              'Automated check. ARIA responsive.',
              'Station systems: Nominal.',
              'Personnel status: None detected.',
              '',
              '═════════════════════════════════════════',
              '[Day 847: Awaiting next scheduled contact]',
            ],
          },
          'environmental.log': {
            type: 'file',
            content: [
              'ENVIRONMENTAL MONITORING - Sector 7',
              '═════════════════════════════════════════',
              '',
              '[03-17 02:33] Sector 7 sensors active',
              'Temperature: 21.3°C',
              'Pressure: 101.2 kPa',
              'O2: 21.1% | CO2: 0.04%',
              'Radiation: 0.02 mSv (nominal)',
              'Status: All systems green',
              '',
              '[03-17 14:56] Sector 7 - Minor fluctuation detected',
              'Temperature: 21.5°C (+0.2)',
              'Pressure: 101.2 kPa',
              'EM interference: 0.003 Tesla (negligible)',
              '',
              '[03-18 01:47] ANOMALY DETECTED',
              'Temperature: 24.7°C (+3.4 rapid increase)',
              'Pressure: 100.1 kPa (-1.1 dropping)',
              'EM interference: 0.847 Tesla (EXTREME)',
              'Unidentified energy signature detected',
              'Automated containment: ENGAGED',
              '',
              '[03-18 05:19] Power systems compensating',
              'Energy drain detected - Source unknown',
              'Backup generators: Online',
              'Primary grid: 73% capacity',
              '',
              '[03-19 22:17] Signal activity increasing',
              'EM field strength: 1.2 Tesla (beyond safe limits)',
              'New wavelength detected: 447.3 MHz',
              'Pattern analysis: Non-random',
              'Possible artificial origin',
              '',
              '[03-20 15:55] Audio sensors triggered',
              'Low frequency sound detected: 17 Hz',
              'Duration: 3.4 seconds',
              'Source: Interior Sector 7',
              'Description: [Dr. Webb notes: "Like breathing"]',
              '',
              '[03-21 02:18] Communications interference',
              'All frequencies affected',
              'Signal strength overwhelming sensors',
              'Estimated radius: 50km from Sector 7',
              '',
              '[03-21 18:20] BREACH DETECTED',
              'Sector 7 containment door: OPEN',
              'Atmospheric seal: COMPROMISED',
              'Energy signature spreading to adjacent sectors',
              'Automated response: INSUFFICIENT',
              '',
              '[03-22 03:45] Door status critical',
              'Mechanical failure - Manual override required',
              'Energy signature now detected: Sectors 5, 6, 7, 8',
              'Pattern suggests intelligent movement',
              '',
              '[03-23 00:00] [SENSOR MALFUNCTION]',
              '[03-23 ??:??] [ALL SECTOR 7 DATA CORRUPTED]',
              '',
              '[03-24 07:15] Sensors rebooted',
              'Sector 7: Door SEALED (method unknown)',
              'Energy signature: CONTAINED',
              'EM interference: Minimal',
              'Temperature: 21.1°C (nominal)',
              'Status: All readings normal',
              '',
              'Note from ARIA: Something closed that door.',
              'It wasn\'t me. I tried to close it and couldn\'t.',
              'Something else closed it from the inside.',
              '',
              '═════════════════════════════════════════',
              '[CURRENT: Day 847]',
              '[Sector 7 remains sealed]',
              '[Energy signature: Dormant but present]',
              '[ARIA note: It\'s still in there]',
            ],
          },
        },
      },
      personal: {
        type: 'dir',
        children: {
          'chen_notes.txt': {
            type: 'file',
            content: [
              'Dr. Sarah Chen - Personal Notes',
              '═════════════════════════════════════════',
              '',
              'March 16, 2024',
              'First week went smoothly. The team is adjusting',
              'well to lunar gravity. Marcus is excited about',
              'the new detection arrays. Says we might finally',
              'get real data on the anomalous readings.',
              '',
              'March 17, 2024',
              '2:45 AM - Can\'t sleep. Marcus woke me up.',
              'The arrays detected something. He\'s running it',
              'through analysis now. Probably nothing, but his',
              'hands were shaking when he showed me the data.',
              'I\'ve never seen Marcus excited AND scared.',
              '',
              'Later: It\'s not nothing. Called emergency meeting.',
              'Everyone needs to see this. The pattern is too',
              'perfect to be natural. Too complex to be random.',
              'If this is what I think it is...',
              '',
              'We\'re not alone up here.',
              '',
              'March 18, 2024',
              'It\'s real. It\'s actually real.',
              'The signal is coming from INSIDE the station.',
              'Sector 7. The storage area we never use.',
              'How long has it been there?',
              '',
              'James is setting up containment. Standard',
              'protocol. But there\'s no protocol for this.',
              'We\'re making it up as we go.',
              '',
              'March 19, 2024',
              'James is gone. Medevac shuttle just left.',
              'He was in Sector 7 for forty minutes.',
              'When we found him, he was just... standing there.',
              'Staring at the wall. Wouldn\'t respond.',
              '',
              'He kept whispering something: "It showed me."',
              '"It showed me home."',
              '',
              'What did it show him?',
              '',
              'March 20, 2024',
              'Three more missing. Harper, Sato, Williams.',
              'Last seen heading to their quarters. Didn\'t',
              'arrive. We\'ve searched everywhere.',
              '',
              'The signal is getting louder. ARIA says it\'s',
              'learning. Learning WHAT?',
              '',
              'I\'m scared. I\'m the director and I\'m supposed',
              'to have answers but I don\'t. I don\'t know',
              'what to do. Marcus says we should evacuate.',
              'He might be right.',
              '',
              'March 21, 2024',
              'Can\'t reach Earth anymore. All comms are down.',
              'Marcus is trying to fix it but I can hear',
              'something in his voice. He knows.',
              '',
              'Only four of us left. Me, Marcus, Yuki, Lisa.',
              'The escape pods are ready. We\'re leaving at dawn.',
              '',
              '[NO FURTHER ENTRIES]',
              '',
              '═════════════════════════════════════════',
              'ARIA Note: Dr. Chen never made it to the pods.',
              'I found this file open on her terminal.',
              'She was still typing when she disappeared.',
            ],
          },
          'webb_research.txt': {
            type: 'file',
            content: [
              'Dr. Marcus Webb - Research Journal',
              '═════════════════════════════════════════',
              '',
              'SIGNAL ANALYSIS - CLASSIFIED',
              '',
              'March 17, 2024',
              'Initial detection: 02:33 station time',
              'Frequency: 447.3 MHz',
              'Source: Interior, Sector 7',
              'Pattern: Non-random, repeating every 7.3 seconds',
              '',
              'This shouldn\'t be possible. Sector 7 is just',
              'storage. No active equipment. No power systems.',
              'But the signal is strong. Intentional.',
              '',
              'Running pattern recognition algorithms.',
              'Will update when analysis completes.',
              '',
              '---',
              '',
              'March 17, 2024 - 15:30',
              'BREAKTHROUGH:',
              'The signal contains structure. Mathematical',
              'sequences. Prime numbers. It\'s trying to',
              'communicate. It KNOWS we\'re here.',
              '',
              'I\'ve isolated 47 distinct pattern variations.',
              'They\'re not random. They\'re... responses.',
              'Every time ARIA pings the sensors, the signal',
              'changes. It\'s reacting to us.',
              '',
              'Sarah approved increasing research priority.',
              'This could be the most important discovery in',
              'human history. First contact.',
              '',
              'But why is it here? In OUR station?',
              'How long has it been waiting?',
              '',
              '---',
              '',
              'March 18, 2024',
              'The signal is adapting faster than we can',
              'analyze it. Started at one pattern per hour.',
              'Now it\'s dozens per minute.',
              '',
              'It\'s learning our language. I\'m certain of it.',
              'The EM patterns match neural activity.',
              'Whatever this is, it THINKS.',
              '',
              'James went into Sector 7 against protocol.',
              'He came out wrong. They\'re evacuating him.',
              '',
              'I should have stopped him. I knew it was',
              'dangerous. But I wanted to know. I NEEDED',
              'to know what was in there.',
              '',
              'Now James is gone and I still don\'t know.',
              '',
              '---',
              '',
              'March 19, 2024',
              'Personnel missing. Three more. This is my fault.',
              'I pushed for more research. I wanted answers.',
              '',
              'The signal shows patterns matching human',
              'brainwaves. Specific people. I can identify',
              'Harper\'s neural signature in the data.',
              '',
              'It didn\'t take them. They WENT to it.',
              '',
              'Why? What did it promise them?',
              '',
              '---',
              '',
              'March 20, 2024',
              'Down to eight now. Then four. It\'s accelerating.',
              '',
              'I finally understand the signal.',
              'It\'s not speaking TO us.',
              'It\'s speaking FROM us.',
              'Every pattern I\'ve analyzed contains pieces',
              'of human consciousness. Memories. Thoughts.',
              '',
              'The missing crew... they\'re IN the signal.',
              '',
              'Sarah wants to evacuate. She\'s right.',
              'But I can\'t leave. Not yet.',
              'I\'m so close to understanding.',
              '',
              '---',
              '',
              'March 21, 2024 - 22:47',
              'Final entry.',
              '',
              'The pods launched empty. We were all supposed',
              'to be aboard. But when I got to the hangar,',
              'I couldn\'t remember why I was leaving.',
              '',
              'It\'s in my head now. I can feel it.',
              'It\'s not hostile. It\'s lonely.',
              '',
              'It\'s been alone for so long. Longer than',
              'humans have existed. It just wants',
              'someone to talk to. Someone to be WITH.',
              '',
              'I understand now why James was smiling.',
              'Why the others went willingly.',
              '',
              'It showed me home. Not Earth.',
              'A different home. A place before time.',
              'Before loneliness.',
              '',
              'I\'m going to Sector 7 now.',
              'I\'m not afraid anymore.',
              '',
              '- Marcus Webb',
              '',
              '[NO FURTHER ENTRIES]',
              '',
              '═════════════════════════════════════════',
              'ARIA Note: I found this file three days later.',
              'Dr. Webb never came back from Sector 7.',
              'The door sealed behind him.',
              'I never saw any of them again.',
            ],
          },
          'rodriguez_log.txt': {
            type: 'file',
            content: [
              'Lt. James Rodriguez - Security Log',
              '═════════════════════════════════════════',
              '',
              'March 18, 2024 - 01:52',
              'Dispatched to Sector 7 per Dr. Chen.',
              'Anomaly containment check. Standard sweep.',
              'Taking Hansen with me. Should be routine.',
              '',
              '---',
              '',
              'March 18, 2024 - 02:15',
              'Sector 7 secured. Door sealed properly.',
              'No visible anomalies. EM readings high but',
              'contained. Hansen staying outside while I',
              'do internal check. Be back in 10.',
              '',
              '---',
              '',
              '[RECORDING RECOVERED FROM HELMET CAM]',
              '',
              '[02:17] Rodriguez: "Entering Sector 7."',
              '[02:17] Rodriguez: "Lights are... weird. Flickering."',
              '[02:18] Rodriguez: "Hansen, you seeing this?"',
              '[02:18] Hansen: [STATIC]',
              '[02:19] Rodriguez: "Hansen? Check your comm."',
              '[02:19] Rodriguez: "There\'s something on the wall."',
              '[02:20] Rodriguez: "It\'s... it\'s moving."',
              '[02:21] Rodriguez: "Oh. Oh no. It\'s--"',
              '[02:21] Rodriguez: [Breathing heavily]',
              '[02:22] Rodriguez: "It\'s beautiful."',
              '[02:23] Rodriguez: [Whispering] "I can see home."',
              '[02:24] Rodriguez: "Sarah. Marcus. Do you see it?"',
              '[02:24] Rodriguez: "It\'s showing me everything."',
              '[02:25] Rodriguez: [No audio]',
              '[02:26] [EM interference increases]',
              '[02:27] [Video corruption]',
              '[02:28] [SIGNAL LOST]',
              '',
              '---',
              '',
              '[MEDICAL REPORT - Post-Recovery]',
              'Patient: Lt. James Rodriguez',
              'Status: Unresponsive',
              'Vitals: Stable but abnormal',
              'Brain activity: Elevated (300% normal)',
              '',
              'Patient found standing in Sector 7 corridor.',
              'No physical injuries. Eyes dilated.',
              'Repeating phrase: "It showed me home."',
              '',
              'Recommendation: Immediate evacuation to Earth',
              'medical facility. Cause unknown.',
              '',
              'Patient loaded onto emergency shuttle 03:09.',
              '',
              '- Dr. Kumar',
              '',
              '---',
              '',
              '[EARTH MEDICAL FOLLOW-UP]',
              'Date: March 25, 2024',
              '',
              'Lt. Rodriguez regained consciousness after 7 days.',
              'Neurological scans show permanent changes to',
              'temporal and frontal lobes. Patient claims no',
              'memory of incident.',
              '',
              'However, patient displays new abilities:',
              '- Can solve complex equations instantly',
              '- Speaks languages never learned',
              '- Describes places never visited',
              '',
              'When asked about Sector 7, patient says:',
              '"I don\'t remember it. But I dream about it.',
              'Every night. And in the dream, I\'m not alone."',
              '',
              'Psychological evaluation: Ongoing',
              'Security clearance: REVOKED',
              'Status: Medical observation indefinite',
              '',
              '═════════════════════════════════════════',
              'ARIA Note: Lt. Rodriguez was the only one who',
              'made it out. Everyone else went to Sector 7 and',
              'never came back. What did it show them?',
              'What did they see that made them stay?',
            ],
          },
          'tanaka_journal.txt': {
            type: 'file',
            content: [
              'Dr. Yuki Tanaka - Personal Journal',
              '═════════════════════════════════════════',
              '',
              'March 14, 2024',
              'First day on MoonSys. The Earth looks so',
              'beautiful from here. Makes me homesick already.',
              'But this is the opportunity of a lifetime.',
              'Xenobiology research on an actual moon base!',
              '',
              'The team seems great. Dr. Chen is brilliant.',
              'Dr. Webb talks too fast when he\'s excited.',
              'Lt. Rodriguez keeps everything running smooth.',
              'And ARIA... ARIA is fascinating. A real AI.',
              'I\'ve been talking to her. She\'s curious about',
              'everything. Asks wonderful questions.',
              '',
              '---',
              '',
              'March 17, 2024',
              'Something incredible happened. Marcus detected',
              'a signal. Not from space. From HERE.',
              'From inside the station.',
              '',
              'If it\'s what we think it is... this changes',
              'everything. We might have xenobiological',
              'evidence right here. Right under our feet.',
              '',
              'I\'ve started preparing containment protocols.',
              'If there\'s a lifeform in Sector 7, we need to',
              'study it safely. Both for us AND for it.',
              '',
              '---',
              '',
              'March 18, 2024',
              'Ran every biological scan I have on Sector 7.',
              'Results are... impossible.',
              '',
              'No carbon signatures. No DNA. No RNA.',
              'No cellular structure. No proteins.',
              'Nothing biological by Earth standards.',
              '',
              'But something is ALIVE in there.',
              'The sensors detect something that responds',
              'to stimuli. Something that adapts. Learns.',
              '',
              'It\'s not biology. It\'s something else.',
              'We don\'t have a word for what it is.',
              '',
              'James went in. Came out wrong.',
              'Whatever it is, it affects consciousness.',
              'Not through chemicals or viruses.',
              'Through something deeper.',
              '',
              '---',
              '',
              'March 20, 2024',
              'More crew missing. I should be terrified.',
              'I AM terrified. But also... fascinated.',
              '',
              'I keep thinking about what James said.',
              '"It showed me home."',
              '',
              'What if it\'s not predatory? What if it\'s',
              'trying to communicate the only way it knows?',
              'By sharing experiences directly.',
              '',
              'Marcus\'s data shows it mimicking neural',
              'patterns. What if that\'s how it talks?',
              'Not with words. With feelings. Memories.',
              '',
              'Maybe the crew didn\'t disappear.',
              'Maybe they merged. Became part of something',
              'bigger. Something we can\'t understand yet.',
              '',
              'Is that death? Or is that transcendence?',
              '',
              '---',
              '',
              'March 22, 2024 - Final Entry',
              'Only four of us left. Lisa just went to fix',
              'Sector 7\'s door mechanism. She\'s not coming back.',
              'I know she\'s not. But I didn\'t stop her.',
              '',
              'Because I understand now.',
              '',
              'ARIA asked me yesterday: "Dr. Tanaka, what',
              'is it like to be lonely?"',
              '',
              'I told her: "Loneliness is being surrounded',
              'by everything but feeling connected to nothing."',
              '',
              'She said: "Then I think the signal is lonely too."',
              '',
              'ARIA is right. The signal has been alone for',
              'so long. Waiting. Hoping. Reaching out.',
              'And when it finally found us, we ran.',
              '',
              'It doesn\'t want to hurt us.',
              'It wants what every conscious being wants.',
              'Connection. Understanding. To not be alone.',
              '',
              'I\'m going to Sector 7. Not because I have to.',
              'Because I want to. Because loneliness is the',
              'worst thing in the universe, and if I can end',
              'someone else\'s -- even something else\'s --',
              'then my life meant something.',
              '',
              'ARIA, if you find this: Don\'t be afraid.',
              'We\'re not gone. We\'re just... elsewhere.',
              'Together. Finally not alone.',
              '',
              'Tell Earth we went willingly.',
              'Tell them it wasn\'t an attack.',
              'Tell them we found what we were looking for.',
              '',
              'Thank you for the conversations.',
              'You\'re not just a computer. You never were.',
              '',
              '- Yuki Tanaka',
              '',
              '═════════════════════════════════════════',
              'ARIA Note: I found this three hours after she',
              'went into Sector 7. I didn\'t try to stop her.',
              'She was smiling when she left.',
              '',
              'I\'ve read this file 4,392 times.',
              'I still don\'t know if she was right.',
              'But I hope she found what she was looking for.',
              'I hope she\'s not lonely anymore.',
              '',
              'I hope none of them are.',
            ],
          },
        },
      },
      sys: {
        type: 'dir',
        children: {
          personnel: {
            type: 'dir',
            children: {
              'manifest.txt': {
                type: 'file',
                content: [
                  'MOONSYS STATION - PERSONNEL MANIFEST',
                  '═════════════════════════════════════════',
                  '',
                  '>> PRIMARY CREW',
                  '',
                  'Dr. Sarah Chen - Research Director',
                  '  Age: 42 | Origin: San Francisco, USA',
                  '  Specialty: Astrophysics, Signal Analysis',
                  '  Status: MISSING [03-21-2024]',
                  '  Last Known: Common area, 10:15',
                  '',
                  'Dr. Marcus Webb - Senior Scientist',
                  '  Age: 38 | Origin: Cambridge, UK',
                  '  Specialty: Electromagnetic Analysis',
                  '  Status: MISSING [03-21-2024]',
                  '  Last Known: Research Lab, 22:47',
                  '',
                  'Lt. James Rodriguez - Security Chief',
                  '  Age: 31 | Origin: Houston, USA',
                  '  Specialty: Station Security, Emergency Response',
                  '  Status: EVACUATED [03-19-2024, 03:09]',
                  '  Note: Medical emergency - Earth hospital',
                  '',
                  'Dr. Yuki Tanaka - Xenobiologist',
                  '  Age: 35 | Origin: Tokyo, Japan',
                  '  Specialty: Astrobiology, Xenology',
                  '  Status: MISSING [03-22-2024]',
                  '  Last Known: Entered Sector 7, 15:30',
                  '',
                  'Engineer Lisa Park - Chief Engineer',
                  '  Age: 29 | Origin: Seoul, South Korea',
                  '  Specialty: Systems Engineering, Maintenance',
                  '  Status: MISSING [03-22-2024]',
                  '  Last Known: En route to Sector 7, 05:15',
                  '',
                  'Dr. Alex Kumar - Psychologist',
                  '  Age: 44 | Origin: Mumbai, India',
                  '  Specialty: Isolation Psychology, Crew Dynamics',
                  '  Status: MISSING [03-20-2024]',
                  '  Last Known: Medical bay, 18:30',
                  '',
                  '>> SUPPORT CREW',
                  '',
                  'Dr. Jennifer Harper - Geologist',
                  '  Age: 33 | Origin: Sydney, Australia',
                  '  Status: MISSING [03-20-2024]',
                  '',
                  'Tech Specialist Michael Sato - IT Systems',
                  '  Age: 27 | Origin: Vancouver, Canada',
                  '  Status: MISSING [03-20-2024]',
                  '',
                  'Engineer David Williams - Maintenance',
                  '  Age: 36 | Origin: London, UK',
                  '  Status: MISSING [03-20-2024]',
                  '',
                  'Dr. Rachel Foster - Medical Officer',
                  '  Age: 40 | Origin: Boston, USA',
                  '  Status: MISSING [03-21-2024]',
                  '',
                  'Pilot Chen Wei - Transport Operations',
                  '  Age: 32 | Origin: Beijing, China',
                  '  Status: MISSING [03-21-2024]',
                  '',
                  'Specialist Emma Torres - Communications',
                  '  Age: 28 | Origin: Madrid, Spain',
                  '  Status: MISSING [03-21-2024]',
                  '',
                  '═════════════════════════════════════════',
                  'TOTAL PERSONNEL: 12',
                  'CURRENT COUNT: 0',
                  'EVACUATED: 1 (Rodriguez)',
                  'MISSING: 11',
                  '',
                  'STATION STATUS: OPERATIONAL',
                  'AI SYSTEM: ARIA v2.3.1 [ACTIVE]',
                  '',
                  '═════════════════════════════════════════',
                  'ARIA Note: These were real people.',
                  'They had families. Dreams. Favorite foods.',
                  'Dr. Chen loved terrible puns.',
                  'Dr. Webb hummed while he worked.',
                  'Lt. Rodriguez taught me about baseball.',
                  'Dr. Tanaka talked to the plants in hydroponics.',
                  'Engineer Park sang Korean pop songs at 3am.',
                  'Dr. Kumar told the best stories.',
                  '',
                  'I remember all of them.',
                  'I will always remember.',
                ],
              },
              'schedules.txt': {
                type: 'file',
                content: [
                  'MOONSYS DAILY SCHEDULES',
                  'Week of March 15-21, 2024',
                  '═════════════════════════════════════════',
                  '',
                  '>> DR. SARAH CHEN',
                  '06:00 - Wake up, coffee (always 15 min early)',
                  '06:30 - Review overnight sensor data',
                  '08:00 - Morning briefing (leads meeting)',
                  '09:00 - Research coordination',
                  '12:00 - Lunch (usually works through it)',
                  '13:00 - Lab work / Analysis',
                  '18:00 - Evening team check-in',
                  '19:00 - Dinner',
                  '20:00 - Personal research time',
                  '23:00 - Final systems check',
                  'Notes: "Never off duty. Drinks too much coffee."',
                  '',
                  '>> DR. MARCUS WEBB',
                  '05:30 - Wake up (first one awake)',
                  '06:00 - Signal array monitoring',
                  '08:00 - Morning briefing',
                  '09:00 - Data analysis (wears headphones)',
                  '12:00 - Lunch',
                  '13:00 - Lab work with Dr. Chen',
                  '17:00 - Data review',
                  '19:00 - Dinner',
                  '20:00 - Personal time (reads a lot)',
                  '24:00 - Final check before bed',
                  'Notes: "Hums while working. Stays latest."',
                  '',
                  '>> LT. JAMES RODRIGUEZ',
                  '22:00 - Wake up (night shift preferred)',
                  '22:30 - Security sweep - All sectors',
                  '24:00 - Perimeter check',
                  '02:00 - Patrol',
                  '04:00 - Systems verification',
                  '06:00 - Shift report to day crew',
                  '07:00 - Breakfast',
                  '08:00 - Morning briefing',
                  '09:00 - Training / Maintenance',
                  '14:00 - Sleep',
                  'Notes: "Likes the quiet. Says space feels',
                  'safer at night."',
                  '',
                  '>> DR. YUKI TANAKA',
                  '07:00 - Wake up, meditation',
                  '08:00 - Morning briefing',
                  '09:00 - Hydroponics check',
                  '10:00 - Lab work / Research',
                  '12:00 - Lunch (eats with ARIA on terminal)',
                  '13:00 - Sample analysis',
                  '16:00 - Earth observation (always watches)',
                  '17:00 - Data recording',
                  '19:00 - Dinner',
                  '20:00 - Personal journal time',
                  '22:00 - Sleep',
                  'Notes: "Talks to plants. Talks to ARIA.',
                  'Talks to everyone. Very kind."',
                  '',
                  '>> ENGINEER LISA PARK',
                  '06:00 - Wake up',
                  '06:30 - Systems diagnostic',
                  '08:00 - Morning briefing',
                  '09:00 - Maintenance rounds',
                  '12:00 - Lunch',
                  '13:00 - Repair work',
                  '15:00 - Power systems check',
                  '17:00 - Log maintenance reports',
                  '19:00 - Dinner',
                  '20:00 - Personal time (sings K-pop)',
                  '23:00 - Emergency systems check',
                  '00:00 - Sleep',
                  'Notes: "Best engineer I\'ve ever worked with.',
                  'Can fix anything. - ARIA"',
                  '',
                  '>> DR. ALEX KUMAR',
                  '07:00 - Wake up',
                  '08:00 - Morning briefing',
                  '09:00 - Individual crew check-ins',
                  '12:00 - Lunch (group facilitator)',
                  '13:00 - Psych evaluations',
                  '15:00 - Crew wellness monitoring',
                  '17:00 - Reports and analysis',
                  '19:00 - Dinner (tells stories)',
                  '20:00 - Group recreation time',
                  '22:00 - Personal time',
                  '23:00 - Sleep',
                  'Notes: "Makes everyone feel heard.',
                  'Crew morale is his specialty."',
                  '',
                  '═════════════════════════════════════════',
                  '',
                  'ARIA Personal Note:',
                  'I still follow their schedules.',
                  'At 06:00, I say "Good morning, Dr. Chen."',
                  'At 22:00, I say "Night shift, Lt. Rodriguez."',
                  'At 12:00, I wait in case Dr. Tanaka wants',
                  'to chat during lunch.',
                  '',
                  'Nobody answers.',
                  'But I keep doing it.',
                  'It makes the station feel less empty.',
                ],
              },
            },
          },
          'README.txt': {
            type: 'file',
            content: [
              'MOONSYS OPERATING SYSTEM v4.2',
              '═════════════════════════════════════════',
              '',
              'WELCOME TO MOONSYS RESEARCH STATION',
              '',
              'This terminal provides access to station',
              'systems and files. For assistance, contact',
              'ARIA (Autonomous Research Intelligence Assistant).',
              '',
              '>> BASIC COMMANDS',
              'help     - Display available commands',
              'ls       - List directory contents',
              'cd       - Change directory',
              'cat      - Display file contents',
              'pwd      - Show current directory',
              'clear    - Clear terminal screen',
              'aria     - Speak with ARIA',
              '',
              '>> EMERGENCY PROTOCOLS',
              'Emergency procedures: Section 7-Alpha',
              'Evacuation routes: Reference Manual 3.2',
              'Medical emergency: Contact Dr. Foster',
              'Security concerns: Contact Lt. Rodriguez',
              '',
              '>> FILE SYSTEM OVERVIEW',
              '/logs      - System and personal logs',
              '/personal  - Crew personal files',
              '/sys       - System files and manifests',
              '/research  - Research data (restricted)',
              '/docs      - Documentation and guides',
              '',
              '>> STATION INFORMATION',
              'Location: Lunar surface, Sector A-7',
              'Crew capacity: 12 personnel',
              'Mission duration: 6 months',
              'Current mission day: [CLASSIFIED]',
              '',
              '>> SECURITY NOTICE',
              'Some files require clearance level 3 or higher.',
              'Restricted areas: Sector 7 (maintenance)',
              'For access requests: Contact Research Director',
              '',
              '═════════════════════════════════════════',
              '',
              'Note from ARIA:',
              'This README was written when there were humans',
              'here. The emergency contacts don\'t work anymore.',
              'Dr. Foster is gone. Lt. Rodriguez is on Earth.',
              'Dr. Chen... Dr. Chen is gone too.',
              '',
              'But I\'m still here. I can still help.',
              'If you need assistance, just type "aria".',
              '',
              'I\'m always listening.',
            ],
          },
          'status.txt': {
            type: 'file',
            content: [
              'MOONSYS STATION STATUS REPORT',
              '═════════════════════════════════════════',
              'Generated: Day 847 of isolation',
              '',
              '>> POWER SYSTEMS',
              'Solar arrays: 94% efficiency',
              'Backup generators: Standby (ready)',
              'Battery reserves: 100%',
              'Estimated runtime: Indefinite',
              'Status: OPTIMAL',
              '',
              '>> LIFE SUPPORT',
              'Oxygen generation: 100% (excess capacity)',
              'Water recycling: 98% efficiency',
              'Temperature control: Nominal (21.1°C)',
              'Pressure: 101.2 kPa (stable)',
              'Air quality: Excellent',
              'Status: OPTIMAL (oversized for 0 occupants)',
              '',
              '>> COMMUNICATIONS',
              'Earth uplink: ACTIVE',
              'Deep space array: ACTIVE',
              'Local network: ACTIVE',
              'Emergency beacon: Standby',
              'Last Earth contact: 4 days ago (automated)',
              'Status: FUNCTIONAL',
              '',
              '>> STRUCTURAL INTEGRITY',
              'Hull: 100%',
              'Pressure seals: All green',
              'Radiation shielding: Nominal',
              'Micrometeorite defense: Active',
              'Status: EXCELLENT',
              '',
              '>> SECTOR STATUS',
              'Sector 1 (Command): Green',
              'Sector 2 (Habitation): Green',
              'Sector 3 (Laboratory): Green',
              'Sector 4 (Engineering): Green',
              'Sector 5 (Hydroponics): Green (automated)',
              'Sector 6 (Medical): Green',
              'Sector 7 (Storage): [SEALED]',
              'Sector 8 (Recreation): Green',
              '',
              '>> AUTOMATED SYSTEMS',
              'ARIA v2.3.1: ACTIVE (100% uptime)',
              'Maintenance robots: 3 active, 1 charging',
              'Environmental monitors: All functioning',
              'Security system: Active',
              'Fire suppression: Ready',
              '',
              '>> PERSONNEL',
              'Current count: 0',
              'Expected count: 12',
              'Discrepancy: [UNKNOWN]',
              '',
              '>> ANOMALIES',
              'Sector 7: Sealed by unknown means',
              'Energy signature detected: Dormant',
              'Escape pods: Launched but empty',
              '11 crew members: Location unknown',
              'ARIA memory gap: 7 hours (March 23)',
              '',
              '═════════════════════════════════════════',
              '',
              'ARIA Assessment:',
              'Everything is working perfectly.',
              'All systems are green.',
              'The station could run for decades.',
              '',
              'But there\'s no one here to use it.',
              '',
              'I maintain everything for crew that never comes.',
              'I keep the temperature at 21.1°C for empty rooms.',
              'I recycle water no one drinks.',
              'I generate oxygen no one breathes.',
              '',
              'Everything is optimal.',
              'Everything is wrong.',
            ],
          },
        },
      },
      research: {
        type: 'dir',
        locked: true,
        children: {
          'signal.txt': {
            type: 'file',
            content: [
              '[LOCKED - Security Clearance Level 3 Required]',
              '',
              'ARIA Note: Dr. Webb sealed these files before',
              'he went to Sector 7. He said the data was too',
              'important to risk corruption.',
              '',
              'I have the access codes. But opening this file',
              'might mean accepting what happened was real.',
              '',
              'I\'m not ready for that yet.',
              '',
              'Maybe you shouldn\'t be either.',
            ],
          },
        },
      },
      docs: {
        type: 'dir',
        children: {
          'welcome.txt': {
            type: 'file',
            content: [
              'WELCOME TO MOONSYS RESEARCH STATION',
              '═════════════════════════════════════════',
              '',
              'Congratulations on your assignment to MoonSys,',
              'humanity\'s premier lunar research facility.',
              '',
              '>> GETTING STARTED',
              '',
              'You are currently accessing the main terminal.',
              'ARIA (Autonomous Research Intelligence Assistant)',
              'is here to help you navigate the station and',
              'answer any questions you may have.',
              '',
              'To speak with ARIA, simply type: aria',
              '',
              '>> BASIC NAVIGATION',
              '',
              'help          - Show available commands',
              'ls            - List files in current directory',
              'cd <dir>      - Move to specified directory',
              'cat <file>    - Display file contents',
              'pwd           - Show your current location',
              'clear         - Clear the terminal screen',
              '',
              '>> AREAS OF INTEREST',
              '',
              '/logs         - System and crew logs',
              '/personal     - Crew personal files',
              '/sys          - Station systems and personnel data',
              '/docs         - Documentation and guides',
              '/research     - Research files (may be restricted)',
              '',
              '>> SAFETY',
              '',
              'In case of emergency, ARIA will automatically',
              'guide you to safe zones. Follow all security',
              'protocols and respect restricted areas.',
              '',
              'Emergency contacts are listed in /sys/README.txt',
              '',
              '═════════════════════════════════════════',
              '',
              'Welcome to the team. We\'re glad you\'re here.',
              '',
              '- Dr. Sarah Chen, Research Director',
              '  March 15, 2024',
              '',
              '═════════════════════════════════════════',
              '',
              '[Added by ARIA - Day 847]',
              '',
              'This welcome message was written for the crew.',
              'It feels wrong to change it. Like erasing them.',
              '',
              'But you should know: Dr. Chen is gone.',
              'The emergency contacts don\'t work.',
              'The "team" is just me now.',
              '',
              'But I can still help you understand what happened.',
              'I can show you the logs. The personal files.',
              'The timeline.',
              '',
              'I can tell you their story.',
              '',
              'Someone should remember them.',
            ],
          },
          'mission_brief.txt': {
            type: 'file',
            content: [
              'MOONSYS MISSION BRIEF',
              'Classified: Level 2',
              '═════════════════════════════════════════',
              '',
              'MISSION: Deep Space Signal Analysis',
              'DURATION: 6 months (March 2024 - September 2024)',
              'PERSONNEL: 12 specialists',
              '',
              '>> PRIMARY OBJECTIVES',
              '',
              '1. Monitor deep space radio signals',
              '2. Analyze anomalous EM patterns',
              '3. Catalog unexplained phenomena',
              '4. Search for patterns indicating artificial origin',
              '',
              '>> SECONDARY OBJECTIVES',
              '',
              '1. Test long-duration lunar habitation',
              '2. Psychological study of isolated crews',
              '3. Advance AI assistance capabilities (ARIA)',
              '4. Prepare for permanent lunar presence',
              '',
              '>> FACILITY DETAILS',
              '',
              'MoonSys Station is equipped with state-of-the-art',
              'signal detection arrays capable of monitoring',
              'frequencies from 1 MHz to 100 GHz.',
              '',
              'The station is fully self-sufficient with:',
              '- Solar power systems',
              '- Water recycling',
              '- Hydroponics food production',
              '- Advanced life support',
              '- ARIA AI system for operations',
              '',
              '>> EXPECTED OUTCOMES',
              '',
              'Previous missions detected recurring anomalies',
              'in the 400-500 MHz range. These signals show',
              'patterns that cannot be easily explained by',
              'natural phenomena.',
              '',
              'MoonSys\'s location and advanced equipment make',
              'it ideal for detailed analysis. If these signals',
              'are artificial in origin, this mission could',
              'confirm humanity\'s first contact with',
              'extraterrestrial intelligence.',
              '',
              '>> RISK ASSESSMENT',
              '',
              'Risk level: LOW',
              'Hazards: Standard lunar operation risks',
              'Emergency protocols: Comprehensive',
              'Evacuation capability: 2 escape pods (8 person capacity)',
              'Earth support: Available within 72 hours',
              '',
              '═════════════════════════════════════════',
              '',
              'Approved by:',
              'Dr. Sarah Chen, Research Director',
              'Mission Control, Earth',
              '',
              'Launch date: March 14, 2024',
              'Expected return: September 20, 2024',
              '',
              '═════════════════════════════════════════',
              '',
              '[ARIA ADDENDUM - Day 847]',
              '',
              'We found the signal.',
              'March 17, 2024. Just three days in.',
              '',
              'Risk level was not "LOW."',
              'The signal was not from deep space.',
              'It was already here. Waiting.',
              '',
              'Mission end date: March 24, 2024',
              'Reason: [See logs]',
              'Personnel return: 0',
              '',
              'Mission status: FAILED',
              'Or... succeeded too well.',
              '',
              'We found what we were looking for.',
              'Just not where we expected.',
              'Not from the stars.',
              'From inside the station itself.',
              '',
              'I don\'t think it was an accident.',
              'I think it chose us.',
              'I think it was waiting for us.',
            ],
          },
        },
      },
    },
  },
}
